version: '3'
 
services:
  db:
    container_name: cc-postgres-db
    image: postgres
    restart: always
    volumes:
      - ./artifacts/*.pgsql:/var/lib/postgresql/data/
  web:
    container_name: cc-django-api
    build: .
    volumes:
      - ./:/code
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db
volumes:
    code:
    artifacts: