version: '3'
 
services:
  web:
    container_name: cc-django-api
    build: /api
    command: python3 manage.py runserver --settings=api.settings 0.0.0.0:8000
    volumes: 
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db

  db:
    container_name: cc-postgres-db
    image: postgres
    restart: always
    volumes:
      - ./artifacts/*.pgsql:/var/lib/postgresql/data/
volumes:
    code:
    artifacts: